const miniGames={
    run:{title:'🏃 Забег 67',type:'run'},
    shooter:{title:'🎯 67 Shooter',type:'shooter'},
    match:{title:'🧩 67 Match',type:'match'}
};
let miniState=null,miniFrame=0,miniTimer=null;
function openMiniGame(type){const g=miniGames[type];if(!g)return;document.getElementById('miniTitle').textContent=g.title;document.getElementById('miniOverlay').classList.add('active');startMiniGame(type)}
function closeMiniGame(){cancelAnimationFrame(miniFrame);clearInterval(miniTimer);document.getElementById('miniOverlay').classList.remove('active');miniState=null}
function startMiniGame(type){cancelAnimationFrame(miniFrame);clearInterval(miniTimer);const c=document.getElementById('miniCanvas'),x=c.getContext('2d'),d=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*d;c.height=h*d;x.scale(d,d);miniState={type,w,h,score:0,time:30,items:[],player:{x:w*.15,y:h*.5,vy:0}};document.getElementById('miniScore').textContent='0';if(type==='match')drawMatch(x);else if(type==='shooter')startShooter(x);else startRun(x)}
function rewardMini(score){const reward=Math.max(50,Math.floor(score)*10);game.coins+=reward;game.totalEarned+=reward;addExperience(Math.floor(score/10)+1);notify('🎉 Мини-игра: +'+reward+' 67!');updateGame()}
function startRun(x){const s=miniState;x.canvas.onclick=()=>s.player.vy=-7;x.canvas.ontouchstart=e=>{e.preventDefault();s.player.vy=-7};let last=performance.now();function loop(t){const dt=Math.min(32,t-last)/16;last=t;s.player.vy+=.38*dt;s.player.y+=s.player.vy*dt;if(s.player.y<12||s.player.y>s.h-25)return endMini();if(Math.random()<.035){const gap=100+Math.random()*70;const top=20+Math.random()*(s.h-gap-40);s.items.push({x:s.w+20,top,gap})}s.items.forEach(o=>o.x-=4*dt);s.items=s.items.filter(o=>o.x>-50);for(const o of s.items){if(s.player.x+18>o.x&&s.player.x-18<o.x+35&&(s.player.y<o.top||s.player.y>o.top+o.gap))return endMini();if(!o.hit&&o.x+35<s.player.x){o.hit=true;s.score+=10}}drawRun(x);document.getElementById('miniScore').textContent=s.score;miniFrame=requestAnimationFrame(loop)}miniFrame=requestAnimationFrame(loop)}
function drawRun(x){const s=miniState;x.clearRect(0,0,s.w,s.h);x.fillStyle='#15102b';x.fillRect(0,0,s.w,s.h);x.fillStyle='#8157ff';s.items.forEach(o=>{x.fillRect(o.x,0,35,o.top);x.fillRect(o.x,o.top+o.gap,35,s.h)});x.fillStyle='#ffd7b5';x.beginPath();x.arc(s.player.x,s.player.y,18,0,7);x.fill();x.fillStyle='#8157ff';x.fillRect(s.player.x-18,s.player.y+15,36,25);x.fillStyle='#fff';x.font='bold 14px Arial';x.fillText('67',s.player.x-10,s.player.y+5)}
function startShooter(x){const s=miniState;x.canvas.onclick=e=>{const r=x.canvas.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;let hit=false;s.items=s.items.filter(o=>{if(Math.hypot(o.x-mx,o.y-my)<o.r){hit=true;s.score+=10;return false}return true});if(!hit)s.score=Math.max(0,s.score-2)};miniTimer=setInterval(()=>{s.time--;if(s.time<=0)endMini();document.getElementById('miniTime').textContent=s.time+'с'},1000);function loop(){if(!miniState)return;s.items.push({x:30+Math.random()*(s.w-60),y:45+Math.random()*(s.h-90),r:18+Math.random()*8,life:0});s.items.forEach(o=>o.life++);s.items=s.items.filter(o=>o.life<90);drawShooter(x);document.getElementById('miniScore').textContent=s.score;miniFrame=requestAnimationFrame(loop)}loop()}
function drawShooter(x){const s=miniState;x.clearRect(0,0,s.w,s.h);x.fillStyle='#090914';x.fillRect(0,0,s.w,s.h);s.items.forEach(o=>{x.beginPath();x.arc(o.x,o.y,o.r,0,7);x.fillStyle='#ff4fc3';x.fill();x.fillStyle='#fff';x.font='bold 12px Arial';x.fillText('67',o.x-8,o.y+4)})}
function drawMatch(x){const s=miniState,n=6,cell=Math.min(s.w/n,55),offX=(s.w-cell*n)/2,offY=20;for(let i=0;i<n;i++)for(let j=0;j<n;j++){x.fillStyle=['#8157ff','#ff4fc3','#35e8ff','#ffd34d'][Math.floor(Math.random()*4)];x.fillRect(offX+j*cell+3,offY+i*cell+3,cell-6,cell-6)}x.fillStyle='#fff';x.font='bold 15px Arial';x.fillText('Нажми на поле, чтобы получить 67',20,s.h-20);x.canvas.onclick=()=>{s.score+=25;document.getElementById('miniScore').textContent=s.score;drawMatch(x)}}
function endMini(){cancelAnimationFrame(miniFrame);clearInterval(miniTimer);if(miniState){rewardMini(miniState.score);notify('🏁 Результат: '+miniState.score)} }
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('openRun')?.addEventListener('click',()=>openMiniGame('run'));document.getElementById('openShooter')?.addEventListener('click',()=>openMiniGame('shooter'));document.getElementById('openMatch')?.addEventListener('click',()=>openMiniGame('match'));document.getElementById('closeMini')?.addEventListener('click',closeMiniGame);document.getElementById('restartMini')?.addEventListener('click',()=>miniState&&startMiniGame(miniState.type))});