const miniGames={run:{title:'🏃 Забег 67',type:'run'},shooter:{title:'🎯 67 Shooter',type:'shooter'},match:{title:'🧩 67 Match',type:'match'}};
let miniState=null,miniFrame=0,miniTimer=null;
const $=id=>document.getElementById(id);
function openMiniGame(type){const g=miniGames[type];if(!g)return;$('miniTitle').textContent=g.title;$('miniOverlay').classList.add('active');startMiniGame(type)}
function closeMiniGame(){cancelAnimationFrame(miniFrame);clearInterval(miniTimer);$('miniOverlay').classList.remove('active');miniState=null}
function resizeCanvas(c){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);return{x,w:r.width,h:r.height}}
function rewardMini(score){if(!game||score<=0)return;const reward=Math.max(50,Math.floor(score)*10);game.coins+=reward;game.totalEarned+=reward;addExperience(Math.max(1,Math.floor(score/10)));notify('🎉 +'+reward+' 67 за мини-игру');updateGame()}
function startMiniGame(type){cancelAnimationFrame(miniFrame);clearInterval(miniTimer);const c=$('miniCanvas'),v=resizeCanvas(c);miniState={type,w:v.w,h:v.h,score:0,time:30,over:false,items:[],particles:[],combo:0};$('miniScore').textContent='0';$('miniTime').textContent=type==='shooter'?'30с':'';if(type==='run')runGame(c,v.x);if(type==='shooter')shooterGame(c,v.x);if(type==='match')matchGame(c,v.x)}
function endMini(){if(!miniState||miniState.over)return;miniState.over=true;cancelAnimationFrame(miniFrame);clearInterval(miniTimer);rewardMini(miniState.score);setTimeout(()=>{if(!miniState)return;const x=$('miniCanvas').getContext('2d');x.save();x.fillStyle='rgba(5,3,15,.8)';x.fillRect(0,0,miniState.w,miniState.h);x.fillStyle='#fff';x.textAlign='center';x.font='900 30px Arial';x.fillText('🏁 Результат',miniState.w/2,miniState.h/2-20);x.font='900 22px Arial';x.fillText(miniState.score+' очков',miniState.w/2,miniState.h/2+20);x.restore()},50)}
function runGame(c,x){const s=miniState;s.player={x:s.w*.2,y:s.h*.5,vy:0,rot:0};s.speed=4;s.distance=0;s.spawn=0;c.onpointerdown=e=>{if(s.over)return;s.player.vy=-8};let last=performance.now();function loop(t){if(s.over)return;const dt=Math.min(32,t-last)/16;last=t;s.speed=Math.min(9,4+s.distance/1800);s.distance+=s.speed*dt;s.score=Math.floor(s.distance/10);s.player.vy+=.42*dt;s.player.y+=s.player.vy*dt;s.player.rot=Math.max(-.35,Math.min(.8,s.player.vy*.06));s.spawn-=dt;if(s.spawn<=0){const gap=Math.max(92,150-s.distance/100);const top=25+Math.random()*(s.h-gap-60);s.items.push({x:s.w+30,top,gap,w:42,passed:false});s.spawn=Math.max(42,78-s.distance/500)}s.items.forEach(o=>o.x-=s.speed*dt);s.items=s.items.filter(o=>o.x>-60);for(const o of s.items){if(!o.passed&&o.x+o.w<s.player.x){o.passed=true;s.score+=15;s.combo=(s.combo||0)+1}if(s.player.x+20>o.x&&s.player.x-20<o.x+o.w&&(s.player.y-20<o.top||s.player.y+20>o.top+o.gap))return endMini()}if(s.player.y<20||s.player.y>s.h-20)return endMini();drawRun(x);$('miniScore').textContent=s.score;miniFrame=requestAnimationFrame(loop)}miniFrame=requestAnimationFrame(loop)}
function drawRun(x){const s=miniState;x.clearRect(0,0,s.w,s.h);const g=x.createLinearGradient(0,0,0,s.h);g.addColorStop(0,'#100d2a');g.addColorStop(1,'#25104b');x.fillStyle=g;x.fillRect(0,0,s.w,s.h);x.fillStyle='rgba(255,255,255,.12)';for(let i=0;i<25;i++){const xx=(i*97-(s.distance*1.5)%97);x.fillRect(xx,25+(i*47)%Math.max(30,s.h-50),2,2)}x.fillStyle='#8157ff';s.items.forEach(o=>{roundRect(x,o.x,0,o.w,o.top,10);roundRect(x,o.x,o.top+o.gap,o.w,s.h,10)});x.save();x.translate(s.player.x,s.player.y);x.rotate(s.player.rot);x.fillStyle='#8157ff';roundRect(x,-25,-18,50,40,12);x.fillStyle='#fff';x.font='900 15px Arial';x.textAlign='center';x.fillText('67',0,5);x.restore()}
function shooterGame(c,x){const s=miniState;s.spawn=0;s.time=30;c.onpointerdown=e=>{if(s.over)return;const r=c.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;let hit=-1;for(let i=s.items.length-1;i>=0;i--){const o=s.items[i];if(Math.hypot(o.x-mx,o.y-my)<o.r+8){hit=i;break}}if(hit>=0){const o=s.items.splice(hit,1)[0];s.combo++;s.score+=10+s.combo*2;for(let i=0;i<12;i++)s.particles.push({x:o.x,y:o.y,vx:(Math.random()-.5)*5,vy:(Math.random()-.5)*5,life:25})}else{s.combo=0;s.score=Math.max(0,s.score-3)}};miniTimer=setInterval(()=>{if(!miniState||s.over)return;s.time--;$('miniTime').textContent=s.time+'с';if(s.time<=0)endMini()},1000);let last=performance.now();function loop(t){if(s.over)return;const dt=Math.min(32,t-last)/16;last=t;s.spawn-=dt;if(s.spawn<=0){const special=Math.random()<.12;s.items.push({x:35+Math.random()*(s.w-70),y:45+Math.random()*(s.h-90),r:special?28:21,special,life:0,phase:Math.random()*6});s.spawn=Math.max(9,25-s.score/100)}s.items.forEach(o=>{o.life+=dt;o.y+=Math.sin(o.life*.08+o.phase)*.8*dt});s.items=s.items.filter(o=>o.life<90);s.particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});s.particles=s.particles.filter(p=>p.life>0);drawShooter(x);$('miniScore').textContent=s.score;miniFrame=requestAnimationFrame(loop)}miniFrame=requestAnimationFrame(loop)}
function drawShooter(x){const s=miniState;x.clearRect(0,0,s.w,s.h);x.fillStyle='#080817';x.fillRect(0,0,s.w,s.h);x.strokeStyle='rgba(129,87,255,.15)';for(let i=0;i<s.w;i+=40){x.beginPath();x.moveTo(i,0);x.lineTo(i,s.h);x.stroke()}for(let i=0;i<s.h;i+=40){x.beginPath();x.moveTo(0,i);x.lineTo(s.w,i);x.stroke()}s.particles.forEach(p=>{x.fillStyle='rgba(255,211,77,'+(p.life/25)+')';x.fillRect(p.x,p.y,4,4)});s.items.forEach(o=>{x.beginPath();x.arc(o.x,o.y,o.r,0,Math.PI*2);x.fillStyle=o.special?'#ffd34d':'#ff4fc3';x.shadowBlur=18;x.shadowColor=x.fillStyle;x.fill();x.shadowBlur=0;x.fillStyle='#fff';x.font='900 12px Arial';x.textAlign='center';x.fillText('67',o.x,o.y+4)})}
function matchGame(c,x){const s=miniState,n=6,colors=['#8157ff','#ff4fc3','#35e8ff','#ffd34d'];s.n=n;s.cell=Math.min(54,s.w/n);s.offX=(s.w-s.cell*n)/2;s.offY=18;s.board=Array.from({length:n},()=>Array.from({length:n},()=>Math.floor(Math.random()*4)));s.selected=null;c.onpointerdown=e=>{if(s.over)return;const r=c.getBoundingClientRect(),cx=Math.floor((e.clientX-r.left-s.offX)/s.cell),cy=Math.floor((e.clientY-r.top-s.offY)/s.cell);if(cx<0||cx>=n||cy<0||cy>=n)return;if(!s.selected){s.selected={x:cx,y:cy};return}const a=s.selected;if(Math.abs(a.x-cx)+Math.abs(a.y-cy)===1){[s.board[a.y][a.x],s.board[cy][cx]]=[s.board[cy][cx],s.board[a.y][a.x]];const matches=findMatches(s.board);if(matches.length){s.score+=matches.length*15+(matches.length>3?25:0);matches.forEach(p=>s.board[p.y][p.x]=null);for(let col=0;col<n;col++){const vals=s.board.map(row=>row[col]).filter(v=>v!==null);while(vals.length<n)vals.unshift(Math.floor(Math.random()*4));for(let row=0;row<n;row++)s.board[row][col]=vals[row]}}else{[s.board[a.y][a.x],s.board[cy][cx]]=[s.board[cy][cx],s.board[a.y][a.x]]}}s.selected=null;$('miniScore').textContent=s.score;drawMatch(x)};drawMatch(x)}
function findMatches(b){const out=new Set(),n=b.length;for(let y=0;y<n;y++)for(let x=0;x<n;x++){let v=b[y][x];if(v===null)continue;let h=1;while(x+h<n&&b[y][x+h]===v)h++;if(h>=3)for(let k=0;k<h;k++)out.add(y+','+(x+k));let w=1;while(y+w<n&&b[y+w][x]===v)w++;if(w>=3)for(let k=0;k<w;k++)out.add((y+k)+','+x)}return [...out].map(k=>{const [y,x]=k.split(',').map(Number);return{x,y}})}
function drawMatch(x){const s=miniState;x.clearRect(0,0,s.w,s.h);x.fillStyle='#0c0920';x.fillRect(0,0,s.w,s.h);for(let y=0;y<s.n;y++)for(let col=0;col<s.n;col++){const px=s.offX+col*s.cell,py=s.offY+y*s.cell,v=s.board[y][col];x.fillStyle='rgba(255,255,255,.05)';roundRect(x,px+2,py+2,s.cell-4,s.cell-4,10);if(v!==null){x.fillStyle=['#8157ff','#ff4fc3','#35e8ff','#ffd34d'][v];x.shadowBlur=12;x.shadowColor=x.fillStyle;roundRect(x,px+6,py+6,s.cell-12,s.cell-12,12);x.shadowBlur=0;x.fillStyle='#fff';x.font='900 '+Math.floor(s.cell*.28)+'px Arial';x.textAlign='center';x.fillText('67',px+s.cell/2,py+s.cell/2+5)}}if(s.selected){x.strokeStyle='#fff';x.lineWidth=3;roundRect(x,s.offX+s.selected.x*s.cell+3,s.offY+s.selected.y*s.cell+3,s.cell-6,s.cell-6,12);x.lineWidth=1}}
function roundRect(x,a,b,w,h,r){x.beginPath();x.roundRect(a,b,w,h,r);x.fill()}
document.addEventListener('DOMContentLoaded',()=>{$('openRun')?.addEventListener('click',()=>openMiniGame('run'));$('openShooter')?.addEventListener('click',()=>openMiniGame('shooter'));$('openMatch')?.addEventListener('click',()=>openMiniGame('match'));$('closeMini')?.addEventListener('click',closeMiniGame);$('restartMini')?.addEventListener('click',()=>miniState&&startMiniGame(miniState.type))});